name: hld_project
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter
  iconsax: ^0.0.8
  cupertino_icons: ^1.0.8
  go_router: ^16.2.4
  equatable: ^2.0.7
  firebase_core: ^4.1.1
  firebase_auth: ^6.1.0
  flutter_dotenv: ^6.0.0
  provider: ^6.1.2
  cloud_firestore: 6.0.2
  intl: ^0.19.0
  image_picker: ^1.0.4
  qr_flutter: ^4.1.0
  fl_chart: ^1.1.1
  firebase_storage: 13.0.3
  http: ^1.1.0
  google_fonts: ^6.3.2
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  test: 1.26.2



flutter:
  assets:
    - .env
  uses-material-design: true


fonts:
  - family: Montserrat  # <--- TÊN GIA ĐÌNH FONT (1)
    fonts:
      - asset: assets/fonts/Montserrat-Black.ttf # <--- KIỂM TRA ĐƯỜNG DẪN ĐÚNG CHƯA?
        weight: 900 # <--- KHAI BÁO ĐÂY LÀ FONT 900
      # Mày có thể thêm các file khác nếu muốn
      # - asset: assets/fonts/Montserrat-Bold.ttf
      #   weight: 700
      # - asset: assets/fonts/Montserrat-Regular.ttf
      #   weight: 400